language: python
python:
- '3.6'
sudo: required
services:
- docker

script:

- |-
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    # TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
    docker build -t homectrl .
    docker tag homectrl xmayeur/homectrl
    docker push xmayeur/homectrl
  fi

addons:
  ssh_known_hosts: home.mayeur.be


# https://github.com/dwyl/learn-travis/blob/master/encrypted-ssh-keys-deployment.md
# See https://oncletom.io/2016/travis-ssh-deploy/


# before_deploy:
# - openssl aes-256-cbc -K $encrypted_9ddbacb801a6_key -iv $encrypted_9ddbacb801a6_iv
#   -in deploy_rsa.enc -out /tmp/deploy_rsa -d
# - eval "$(ssh-agent -s)"
# - chmod 600 /tmp/deploy_rsa
# - ssh-add /tmp/deploy_rsa

# deploy:
#  provider: script
#  skip_cleanup: true
#  script: ssh -o "StrictHostKeyChecking no" -t root@home.mayeur.be -p 2202 /root/HomeCtrl.sh

env:
  global: 
  - secure: DPfiMtDuNdyPRLEfbk9ZItUCui9pR+YxuOe7EL1hHuzL3ExLASgo1d0QTRgBO74etdxdjuXy7Ro2slG6zKAgigWw3yelPuyYR+5a9a/JCn9KoC6O+6x+VgfpHPq8gq7tyjzwOMgYq0YfzmqTXXF7mtSSu2oljzqHuPPizk0/xx4QHzwqrx0Qd7U4ULECRJPvl3/AHr+pS4SidkiUB9HKP9nsV2SEMAAA6HEH8MiUCe2bVurLzxx1O2te4d8cHRgbBod7JOXDKTvduynJ45Mj5gKyDIkABzMRWtiYwsLMPBxvSdQdAVBvfgCUDmChv4yxyKGaw/MKNRWHuXbSmRQXO5W1nONIEzF1iRF9OBlxXHx096szsab3KzZOhe/dlNTABoKf8NoZtXlf6YlQYxdz/SHUTh0EaARaVZOBP8q8zPjyavNbOYIVdwH3wSeONIGGmOJyYx3Gl7da5kZwRvkYG4rhobpLXcg/le3lZhiN/o+6kxOVyfPT8ifoKbBkMKZjg8tQbYoVl3L50afJbXK5Z7FdORg2ihIQKwP28sWpfs3ZfhpvJsAd2hZ+4+QlxvT9SFpCaz8scFVHV9+ezDMcRh2i2KvQIyJdgF5q6vcCSdZMOeesPdD4vjfk3YLF3sJ/eigerHjb98d9+4QBc9YfsncipWWmw8/x9cHz2PmrJvo=
  - secure: UTqEeVWsW0ZDsTUB3JKenbRTQLX5shapsiz+JyHmh3RGrqnmKL4a2UbYrdd8vDgyvSUoIaFQCpJUeYohRJaYM+RB/1U/YuXACH7pgItJN5UbgSrbPj498Ln9zgpUFbQ2Isso7x2wCY6ivgnZItRpNR4XpUwvmBrQPxVknzrtvhi1wmemw5kIByBjGuk6IVPpLsIp2u2PjOqlSyLh7UqvMqTbdvSpRzA98PJiLgAIKEgFtA8HVH6lrvuNugf93pMSw/jHCXnQNBOy8R4e4Xngk3rRU4oNnrld6PlCdOhURcqKudj9dphYWd7lO6ZToBGFYo2f/asiV9/3M/4pF9y4fFp1wM89vmx5jNXAiQb6mpXNdiwcjIeTTdZwdc5sQMbE0adW6LSB4H10dVy8iorut/cGzXhrBs0GXTRtM3acHJYxdVT++KIM5fVnhY1gFUWkqn0jIZqfeMi7mxNVOeb3ZCbHZgDo8RlXB6bnPSNSGaEcVpPi5wpca6YjrAyi69xqEhnfSirjvjdvRlfbHpP75mf7vMemYkZRB33jOz8nuEbqrR5o6XY4cciPKqVpKVbZJwRhGr8F30qFre9EkUSE94TjlyK1PnMwnHtxg3zUMFv8qlFT9K1Pbz2g4PPFlJqQjXCi8usNk9bTqro8NiWpr8RQRdQmxElP3ARA0vGzndY=
  - secure: DPfiMtDuNdyPRLEfbk9ZItUCui9pR+YxuOe7EL1hHuzL3ExLASgo1d0QTRgBO74etdxdjuXy7Ro2slG6zKAgigWw3yelPuyYR+5a9a/JCn9KoC6O+6x+VgfpHPq8gq7tyjzwOMgYq0YfzmqTXXF7mtSSu2oljzqHuPPizk0/xx4QHzwqrx0Qd7U4ULECRJPvl3/AHr+pS4SidkiUB9HKP9nsV2SEMAAA6HEH8MiUCe2bVurLzxx1O2te4d8cHRgbBod7JOXDKTvduynJ45Mj5gKyDIkABzMRWtiYwsLMPBxvSdQdAVBvfgCUDmChv4yxyKGaw/MKNRWHuXbSmRQXO5W1nONIEzF1iRF9OBlxXHx096szsab3KzZOhe/dlNTABoKf8NoZtXlf6YlQYxdz/SHUTh0EaARaVZOBP8q8zPjyavNbOYIVdwH3wSeONIGGmOJyYx3Gl7da5kZwRvkYG4rhobpLXcg/le3lZhiN/o+6kxOVyfPT8ifoKbBkMKZjg8tQbYoVl3L50afJbXK5Z7FdORg2ihIQKwP28sWpfs3ZfhpvJsAd2hZ+4+QlxvT9SFpCaz8scFVHV9+ezDMcRh2i2KvQIyJdgF5q6vcCSdZMOeesPdD4vjfk3YLF3sJ/eigerHjb98d9+4QBc9YfsncipWWmw8/x9cHz2PmrJvo=